"""relationship is made in both tables

Revision ID: 8508366a71e9
Revises: d2cb2c0ad491
Create Date: 2025-09-16 14:47:11.638117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8508366a71e9'
down_revision: Union[str, Sequence[str], None] = 'd2cb2c0ad491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
