"""error fixed in a column

Revision ID: 9907ff85a8b8
Revises: fb5fa8a43270
Create Date: 2025-09-15 18:00:30.656144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9907ff85a8b8'
down_revision: Union[str, Sequence[str], None] = 'fb5fa8a43270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students_degree_certificate', sa.Column('roll_number', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('students_degree_certificate_roll_no_key'), 'students_degree_certificate', type_='unique')
    op.create_unique_constraint(None, 'students_degree_certificate', ['roll_number'])
    op.drop_column('students_degree_certificate', 'roll_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students_degree_certificate', sa.Column('roll_no', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'students_degree_certificate', type_='unique')
    op.create_unique_constraint(op.f('students_degree_certificate_roll_no_key'), 'students_degree_certificate', ['roll_no'], postgresql_nulls_not_distinct=False)
    op.drop_column('students_degree_certificate', 'roll_number')
    # ### end Alembic commands ###
