"""update signup table again

Revision ID: f24b8c7cb502
Revises: ff647507be95
Create Date: 2025-09-17 11:49:49.224420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f24b8c7cb502'
down_revision: Union[str, Sequence[str], None] = 'ff647507be95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_signup', sa.Column('username', sa.String(), nullable=False))
    op.create_index(op.f('ix_student_signup_username'), 'student_signup', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_signup_username'), table_name='student_signup')
    op.drop_column('student_signup', 'username')
    # ### end Alembic commands ###
