"""first table prototype

Revision ID: fb5fa8a43270
Revises: 
Create Date: 2025-09-15 14:15:07.375942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5fa8a43270'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students_degree_certificate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('corse_duration', sa.Integer(), nullable=False),
    sa.Column('cgpa', sa.Float(), nullable=False),
    sa.Column('corse_compleated', sa.Boolean(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('age', sa.String(), nullable=False),
    sa.Column('roll_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roll_no')
    )
    op.create_index(op.f('ix_students_degree_certificate_id'), 'students_degree_certificate', ['id'], unique=False)
    op.create_index(op.f('ix_students_degree_certificate_name'), 'students_degree_certificate', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_degree_certificate_name'), table_name='students_degree_certificate')
    op.drop_index(op.f('ix_students_degree_certificate_id'), table_name='students_degree_certificate')
    op.drop_table('students_degree_certificate')
    # ### end Alembic commands ###
