"""update signup table

Revision ID: ff647507be95
Revises: f33720534cd6
Create Date: 2025-09-17 11:30:22.161033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff647507be95'
down_revision: Union[str, Sequence[str], None] = 'f33720534cd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('student_signup_student_id_fkey'), 'student_signup', type_='foreignkey')
    op.drop_column('student_signup', 'student_id')
    op.add_column('students_degree_certificate', sa.Column('student_signup_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students_degree_certificate', 'student_signup', ['student_signup_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students_degree_certificate', type_='foreignkey')
    op.drop_column('students_degree_certificate', 'student_signup_id')
    op.add_column('student_signup', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('student_signup_student_id_fkey'), 'student_signup', 'students_degree_certificate', ['student_id'], ['id'])
    # ### end Alembic commands ###
